spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://localhost:3306/productdb?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:/db/migration
    baseline-on-migrate: true

  ai:
    openai:
      api-key: ${OPENROUTER_API_KEY}
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: openrouter/free

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
